### PR TITLE
[tmp] Perf improvements for multiple wordcloud instances and large datasets

### PR DESCRIPTION
**Pull request by chrisrzhou**
## Summary

Based on the awesome work by @WhoAteDaCake in #33.
- [x] Address debouncing rendering for multiple wordclouds.
- [x] Address improving optimization for large `words` via `options.enableOptimizations`.
- [x] Update docs to inform how it works and that it is not a formally supported feature in future versions.
- [x] Add examples to docs.
- [x] Moved rendering logic to `layout.tsx`.

The goal here is to separate the code in a way that we can deprecate and support `enableOptimizations` in the future without touching the `d3-cloud` source code.  Initially, I went deep into #33 and tried to break it into organizable pieces, but it was too coupled.  I think this approach provides a good balance.

### Bugs
With the code in `optimized-d3-cloud.js`, there seems to be layout rendering bugs where wordclouds are not correctly/completely rendered.

Not sure how to solve this @WhoAteDaCake, and I don't think we should support the feature until we know how to address this.

image

I intend to clean the code up a little and fix some other open issues before releasing a formal (minor) version.

## Testing
Spin docs locally with `yarn dev` and check http://127.0.0.1:3000/usage/optimizations

### CODE REVIEW

**Comment by chrisrzhou** [comment]
@WhoAteDaCake, feel free to use the code accordingly here and apply it to #33 so you contribute to the source code.  This PR is just for discussion and to help debug the rendering layout issues as mentioned in the PR summary.  I'll close this out once we have something more concrete.

**Comment by WhoAteDaCake** [comment]
I'll take a quick look tonight. Will push it to #33 If i find anything out.

**Comment by WhoAteDaCake** [comment]
So the solution I found was in the `optimizations.mdx` swapping `words={words}` to `words={JSON.parse(JSON.stringify(words))}` fixes it.
This is likely to due to the fact that the algorithm modifies the array elements directly instead of creating copies of it.

People could potentially hit this in the future, so one solution is to do:
`.words(clonedeep(sortedWords))` instead of `.words(sortedWords)` In `layout.tsx` (using `lodash.clonedeep` to clone the items)

**Comment by chrisrzhou** [comment]
👍 Nice debugging, and feel free to integrate it in #33.  I agree with you that this is important enough to handle internally in the library.  Closing this PR since we have your code/contributions in the other.  I'll test/merge it tonight once that's addressed!

**Pull request closed without merging**
